/**
 * fonts.ts
 *
 * This file exports a single object containing all available font definitions for the
 * font customization feature. Each font has a display name and the corresponding
 * CSS font-family value.
 */

// Type definition for a single font object
type Font = {
  name: string;
  family: string;
};

// The main fonts object, fully typed and alphabetically sorted
export const fonts: Record<string, Font> = {
  'a-astro-space': { name: 'A Astro Space', family: "'A Astro Space', sans-serif" },
  'abel': { name: 'Abel', family: "'Abel', sans-serif" },
  'abhaya-libre': { name: 'Abhaya Libre', family: "'Abhaya Libre', serif" },
  'abril-fatface': { name: 'Abril Fatface', family: "'Abril Fatface', cursive" },
  'abyssopelagic': { name: 'Abyssopelagic', family: "'Abyssopelagic', sans-serif" },
  'aclonica': { name: 'Aclonica', family: "'Aclonica', sans-serif" },
  'acme': { name: 'Acme', family: "'Acme', sans-serif" },
  'actor': { name: 'Actor', family: "'Actor', sans-serif" },
  'adamina': { name: 'Adamina', family: "'Adamina', serif" },
  'advent-pro': { name: 'Advent Pro', family: "'Advent Pro', sans-serif" },
  'aguafina-script': { name: 'Aguafina Script', family: "'Aguafina Script', cursive" },
  'akronim': { name: 'Akronim', family: "'Akronim', cursive" },
  'aladin': { name: 'Aladin', family: "'Aladin', cursive" },
  'aldrich': { name: 'Aldrich', family: "'Aldrich', sans-serif" },
  'alef': { name: 'Alef', family: "'Alef', sans-serif" },
  'alegreya': { name: 'Alegreya', family: "'Alegreya', serif" },
  'alegreya-sans': { name: 'Alegreya Sans', family: "'Alegreya Sans', sans-serif" },
  'alegreya-sans-sc': { name: 'Alegreya Sans SC', family: "'Alegreya Sans SC', sans-serif" },
  'alex-brush': { name: 'Alex Brush', family: "'Alex Brush', cursive" },
  'alfa-slab-one': { name: 'Alfa Slab One', family: "'Alfa Slab One', cursive" },
  'alice': { name: 'Alice', family: "'Alice', serif" },
  'alike': { name: 'Alike', family: "'Alike', serif" },
  'allan': { name: 'Allan', family: "'Allan', cursive" },
  'allerta': { name: 'Allerta', family: "'Allerta', sans-serif" },
  'allura': { name: 'Allura', family: "'Allura', cursive" },
  'amarante': { name: 'Amarante', family: "'Amarante', cursive" },
  'amaranth': { name: 'Amaranth', family: "'Amaranth', sans-serif" },
  'amatic-sc': { name: 'Amatic SC', family: "'Amatic SC', cursive" },
  'amiri': { name: 'Amiri', family: "'Amiri', serif" },
  'amita': { name: 'Amita', family: "'Amita', cursive" },
  'andika': { name: 'Andika', family: "'Andika', sans-serif" },
  'anton': { name: 'Anton', family: "'Anton', sans-serif" },
  'antipasto': { name: 'Antipasto', family: "'Antipasto', sans-serif" },
  'arapey': { name: 'Arapey', family: "'Arapey', serif" },
  'arbutus': { name: 'Arbutus', family: "'Arbutus', cursive" },
  'architects-daughter': { name: 'Architects Daughter', family: "'Architects Daughter', cursive" },
  'archivo': { name: 'Archivo', family: "'Archivo', sans-serif" },
  'archivo-black': { name: 'Archivo Black', family: "'Archivo Black', sans-serif" },
  'archivo-narrow': { name: 'Archivo Narrow', family: "'Archivo Narrow', sans-serif" },
  'arimo': { name: 'Arimo', family: "'Arimo', sans-serif" },
  'arial': { name: 'Arial', family: 'Arial, sans-serif' },
  'arizonia': { name: 'Arizonia', family: "'Arizonia', cursive" },
  'armata': { name: 'Armata', family: "'Armata', sans-serif" },
  'arsenal': { name: 'Arsenal', family: "'Arsenal', sans-serif" },
  'artifika': { name: 'Artifika', family: "'Artifika', serif" },
  'arvo': { name: 'Arvo', family: "'Arvo', serif" },
  'asap': { name: 'Asap', family: "'Asap', sans-serif" },
  'asset': { name: 'Asset', family: "'Asset', cursive" },
  'assistant': { name: 'Assistant', family: "'Assistant', sans-serif" },
  'astroz': { name: 'Astroz', family: "'Astroz', sans-serif" },
  'atma': { name: 'Atma', family: "'Atma', cursive" },
  'audiowide': { name: 'Audiowide', family: "'Audiowide', cursive" },
  'autour-one': { name: 'Autour One', family: "'Autour One', cursive" },
  'avenir': { name: 'Avenir', family: "'Avenir', sans-serif" },
  'avigea': { name: 'Avigea', family: "'Avigea', serif" },
  'average': { name: 'Average', family: "'Average', serif" },
  'azonix': { name: 'Azonix', family: "'Azonix', sans-serif" },
  'bad-script': { name: 'Bad Script', family: "'Bad Script', cursive" },
  'balsamiq-sans': { name: 'Balsamiq Sans', family: "'Balsamiq Sans', cursive" },
  'bangers': { name: 'Bangers', family: "'Bangers', cursive" },
  'barlow': { name: 'Barlow', family: "'Barlow', sans-serif" },
  'barlow-condensed': { name: 'Barlow Condensed', family: "'Barlow Condensed', sans-serif" },
  'baron-neue': { name: 'Baron Neue', family: "'Baron Neue', sans-serif" },
  'barriecito': { name: 'Barriecito', family: "'Barriecito', cursive" },
  'bebas-neue': { name: 'Bebas Neue', family: "'Bebas Neue', sans-serif" },
  'belgrano': { name: 'Belgrano', family: "'Belgrano', serif" },
  'belleza': { name: 'Belleza', family: "'Belleza', sans-serif" },
  'benchnine': { name: 'BenchNine', family: "'BenchNine', sans-serif" },
  'bentham': { name: 'Bentham', family: "'Bentham', serif" },
  'berkshire-swash': { name: 'Berkshire Swash', family: "'Berkshire Swash', cursive" },
  'besley': { name: 'Besley', family: "'Besley', serif" },
  'bevan': { name: 'Bevan', family: "'Bevan', cursive" },
  'big-shoulders-display': { name: 'Big Shoulders Display', family: "'Big Shoulders Display', cursive" },
  'biryani': { name: 'Biryani', family: "'Biryani', sans-serif" },
  'bitter': { name: 'Bitter', family: "'Bitter', serif" },
  'black-ops-one': { name: 'Black Ops One', family: "'Black Ops One', cursive" },
  'blanka': { name: 'Blanka', family: "'Blanka', sans-serif" },
  'bonbon': { name: 'Bonbon', family: "'Bonbon', cursive" },
  'boogaloo': { name: 'Boogaloo', family: "'Boogaloo', cursive" },
  'bowlby-one-sc': { name: 'Bowlby One SC', family: "'Bowlby One SC', cursive" },
  'bree-serif': { name: 'Bree Serif', family: "'Bree Serif', serif" },
  'bricolage-grotesque': { name: 'Bricolage Grotesque', family: "'Bricolage Grotesque', sans-serif" },
  'brush-script-mt': { name: 'Brush Script MT', family: "'Brush Script MT', cursive" },
  'bungee': { name: 'Bungee', family: "'Bungee', cursive" },
  'butler': { name: 'Butler', family: "'Butler', serif" },
  'cabin': { name: 'Cabin', family: "'Cabin', sans-serif" },
  'cairo': { name: 'Cairo', family: "'Cairo', sans-serif" },
  'calistoga': { name: 'Calistoga', family: "'Calistoga', cursive" },
  'calligraffitti': { name: 'Calligraffitti', family: "'Calligraffitti', cursive" },
  'cambria': { name: 'Cambria', family: 'Cambria, serif' },
  'canavar': { name: 'Canavar', family: "'Canavar', sans-serif" },
  'candal': { name: 'Candal', family: "'Candal', sans-serif" },
  'cantarell': { name: 'Cantarell', family: "'Cantarell', sans-serif" },
  'carter-one': { name: 'Carter One', family: "'Carter One', cursive" },
  'catamaran': { name: 'Catamaran', family: "'Catamaran', sans-serif" },
  'caudex': { name: 'Caudex', family: "'Caudex', serif" },
  'caveat': { name: 'Caveat', family: "'Caveat', cursive" },
  'cedarville-cursive': { name: 'Cedarville Cursive', family: "'Cedarville Cursive', cursive" },
  'changa': { name: 'Changa', family: "'Changa', sans-serif" },
  'changa-one': { name: 'Changa One', family: "'Changa One', cursive" },
  'charmonman': { name: 'Charmonman', family: "'Charmonman', cursive" },
  'chau-philomene-one': { name: 'Chau Philomene One', family: "'Chau Philomene One', sans-serif" },
  'chewy': { name: 'Chewy', family: "'Chewy', cursive" },
  'cinzel': { name: 'Cinzel', family: "'Cinzel', serif" },
  'cinzel-decorative': { name: 'Cinzel Decorative', family: "'Cinzel Decorative', cursive" },
  'clicker-script': { name: 'Clicker Script', family: "'Clicker Script', cursive" },
  'coco-gothic': { name: 'Coco Gothic', family: "'Coco Gothic', sans-serif" },
  'coda': { name: 'Coda', family: "'Coda', cursive" },
  'comfortaa': { name: 'Comfortaa', family: "'Comfortaa', cursive" },
  'coming-soon': { name: 'Coming Soon', family: "'Coming Soon', cursive" },
  'concert-one': { name: 'Concert One', family: "'Concert One', cursive" },
  'condiment': { name: 'Condiment', family: "'Condiment', cursive" },
  'consolas': { name: 'Consolas', family: 'Consolas, monospace' },
  'cookie': { name: 'Cookie', family: "'Cookie', cursive" },
  'cormorant': { name: 'Cormorant', family: "'Cormorant', serif" },
  'cormorant-garamond': { name: 'Cormorant Garamond', family: "'Cormorant Garamond', serif" },
  'courier-new': { name: 'Courier New', family: "'Courier New', monospace" },
  'courgette': { name: 'Courgette', family: "'Courgette', cursive" },
  'crete-round': { name: 'Crete Round', family: "'Crete Round', serif" },
  'crimson-text': { name: 'Crimson Text', family: "'Crimson Text', serif" },
  'cuprum': { name: 'Cuprum', family: "'Cuprum', sans-serif" },
  'damion': { name: 'Damion', family: "'Damion', cursive" },
  'dancing-script': { name: 'Dancing Script', family: "'Dancing Script', cursive" },
  'didot': { name: 'Didot', family: 'Didot, serif' },
  'domine': { name: 'Domine', family: "'Domine', serif" },
  'dosis': { name: 'Dosis', family: "'Dosis', sans-serif" },
  'droid-sans': { name: 'Droid Sans', family: "'Droid Sans', sans-serif" },
  'droid-serif': { name: 'Droid Serif', family: "'Droid Serif', serif" },
  'eb-garamond': { name: 'EB Garamond', family: "'EB Garamond', serif" },
  'eco-gothic': { name: 'Eco Gothic', family: "'Eco Gothic', sans-serif" },
  'el-messiri': { name: 'El Messiri', family: "'El Messiri', sans-serif" },
  'elianto': { name: 'Elianto', family: "'Elianto', sans-serif" },
  'emilys-candy': { name: 'Emilys Candy', family: "'Emilys Candy', cursive" },
  'encode-sans': { name: 'Encode Sans', family: "'Encode Sans', sans-serif" },
  'engagement': { name: 'Engagement', family: "'Engagement', cursive" },
  'enriqueta': { name: 'Enriqueta', family: "'Enriqueta', serif" },
  'existence-light': { name: 'Existence Light', family: "'Existence Light', sans-serif" },
  'exo-2': { name: 'Exo 2', family: "'Exo 2', sans-serif" },
  'expletus-sans': { name: 'Expletus Sans', family: "'Expletus Sans', cursive" },
  'fascinate-inline': { name: 'Fascinate Inline', family: "'Fascinate Inline', cursive" },
  'fauna-one': { name: 'Fauna One', family: "'Fauna One', serif" },
  'faustina': { name: 'Faustina', family: "'Faustina', serif" },
  'federo': { name: 'Federo', family: "'Federo', sans-serif" },
  'finger-paint': { name: 'Finger Paint', family: "'Finger Paint', cursive" },
  'fira-code': { name: 'Fira Code', family: "'Fira Code', monospace" },
  'fira-mono': { name: 'Fira Mono', family: "'Fira Mono', monospace" },
  'fira-sans': { name: 'Fira Sans', family: "'Fira Sans', sans-serif" },
  'fjalla-one': { name: 'Fjalla One', family: "'Fjalla One', sans-serif" },
  'fondamento': { name: 'Fondamento', family: "'Fondamento', cursive" },
  'francois-one': { name: 'Francois One', family: "'Francois One', sans-serif" },
  'frank-ruhl-libre': { name: 'Frank Ruhl Libre', family: "'Frank Ruhl Libre', serif" },
  'fredoka-one': { name: 'Fredoka One', family: "'Fredoka One', cursive" },
  'fugaz-one': { name: 'Fugaz One', family: "'Fugaz One', cursive" },
  'gabriela': { name: 'Gabriela', family: "'Gabriela', serif" },
  'gafata': { name: 'Gafata', family: "'Gafata', sans-serif" },
  'garamond': { name: 'Garamond', family: 'Garamond, serif' },
  'gentium-book-basic': { name: 'Gentium Book Basic', family: "'Gentium Book Basic', serif" },
  'georgia': { name: 'Georgia', family: 'Georgia, serif' },
  'gfs-didot': { name: 'GFS Didot', family: "'GFS Didot', serif" },
  'gilroy-bold': { name: 'Gilroy-Bold', family: "'Gilroy-Bold', sans-serif" },
  'gilda-display': { name: 'Gilda Display', family: "'Gilda Display', serif" },
  'give-you-glory': { name: 'Give You Glory', family: "'Give You Glory', cursive" },
  'glegoo': { name: 'Glegoo', family: "'Glegoo', serif" },
  'gloria-hallelujah': { name: 'Gloria Hallelujah', family: "'Gloria Hallelujah', cursive" },
  'goblin-one': { name: 'Goblin One', family: "'Goblin One', cursive" },
  'goudy-bookletter-1911': { name: 'Goudy Bookletter 1911', family: "'Goudy Bookletter 1911', serif" },
  'graduate': { name: 'Graduate', family: "'Graduate', cursive" },
  'grand-hotel': { name: 'Grand Hotel', family: "'Grand Hotel', cursive" },
  'great-vibes': { name: 'Great Vibes', family: "'Great Vibes', cursive" },
  'gruppo': { name: 'Gruppo', family: "'Gruppo', sans-serif" },
  'hammersmith-one': { name: 'Hammersmith One', family: "'Hammersmith One', sans-serif" },
  'hanuman': { name: 'Hanuman', family: "'Hanuman', serif" },
  'happy-monkey': { name: 'Happy Monkey', family: "'Happy Monkey', cursive" },
  'heebo': { name: 'Heebo', family: "'Heebo', sans-serif" },
  'helvetica': { name: 'Helvetica', family: 'Helvetica, sans-serif' },
  'henny-penny': { name: 'Henny Penny', family: "'Henny Penny', cursive" },
  'hind': { name: 'Hind', family: "'Hind', sans-serif" },
  'holtwood-one-sc': { name: 'Holtwood One SC', family: "'Holtwood One SC', serif" },
  'homemade-apple': { name: 'Homemade Apple', family: "'Homemade Apple', cursive" },
  'ibm-plex-mono': { name: 'IBM Plex Mono', family: "'IBM Plex Mono', monospace" },
  'ibm-plex-sans': { name: 'IBM Plex Sans', family: "'IBM Plex Sans', sans-serif" },
  'ibm-plex-serif': { name: 'IBM Plex Serif', family: "'IBM Plex Serif', serif" },
  'iceberg': { name: 'Iceberg', family: "'Iceberg', cursive" },
  'impact': { name: 'Impact', family: 'Impact, sans-serif' },
  'inconsolata': { name: 'Inconsolata', family: "'Inconsolata', monospace" },
  'indie-flower': { name: 'Indie Flower', family: "'Indie Flower', cursive" },
  'inter': { name: 'Inter', family: "'Inter', sans-serif" },
  'istok-web': { name: 'Istok Web', family: "'Istok Web', sans-serif" },
  'italiana': { name: 'Italiana', family: "'Italiana', serif" },
  'jetbrains-mono': { name: 'JetBrains Mono', family: "'JetBrains Mono', monospace" },
  'jockey-one': { name: 'Jockey One', family: "'Jockey One', sans-serif" },
  'josefin-sans': { name: 'Josefin Sans', family: "'Josefin Sans', sans-serif" },
  'josefin-slab': { name: 'Josefin Slab', family: "'Josefin Slab', serif" },
  'jost': { name: 'Jost', family: "'Jost', sans-serif" },
  'jura': { name: 'Jura', family: "'Jura', sans-serif" },
  'just-another-hand': { name: 'Just Another Hand', family: "'Just Another Hand', cursive" },
  'kalam': { name: 'Kalam', family: "'Kalam', cursive" },
  'kanit': { name: 'Kanit', family: "'Kanit', sans-serif" },
  'karma': { name: 'Karma', family: "'Karma', serif" },
  'kaushan-script': { name: 'Kaushan Script', family: "'Kaushan Script', cursive" },
  'khand': { name: 'Khand', family: "'Khand', sans-serif" },
  'kranky': { name: 'Kranky', family: "'Kranky', cursive" },
  'kreon': { name: 'Kreon', family: "'Kreon', serif" },
  'kristi': { name: 'Kristi', family: "'Kristi', cursive" },
  'lato': { name: 'Lato', family: "'Lato', sans-serif" },
  'league-spartan': { name: 'League Spartan', family: "'League Spartan', sans-serif" },
  'leckerli-one': { name: 'Leckerli One', family: "'Leckerli One', cursive" },
  'ledger': { name: 'Ledger', family: "'Ledger', serif" },
  'lekton': { name: 'Lekton', family: "'Lekton', sans-serif" },
  'lexend': { name: 'Lexend', family: "'Lexend', sans-serif" },
  'libre-baskerville': { name: 'Libre Baskerville', family: "'Libre Baskerville', serif" },
  'libre-franklin': { name: 'Libre Franklin', family: "'Libre Franklin', sans-serif" },
  'lilita-one': { name: 'Lilita One', family: "'Lilita One', cursive" },
  'limelight': { name: 'Limelight', family: "'Limelight', cursive" },
  'livingston': { name: 'Livingston', family: "'Livingston', serif" },
  'lobster': { name: 'Lobster', family: "'Lobster', cursive" },
  'lobster-two': { name: 'Lobster Two', family: "'Lobster Two', cursive" },
  'london': { name: 'London', family: "'London', sans-serif" },
  'lora': { name: 'Lora', family: "'Lora', serif" },
  'lucida-console': { name: 'Lucida Console', family: "'Lucida Console', monospace" },
  'luckiest-guy': { name: 'Luckiest Guy', family: "'Luckiest Guy', cursive" },
  'lustria': { name: 'Lustria', family: "'Lustria', serif" },
  'luxia': { name: 'Luxia', family: "'Luxia', serif" },
  'luxiachy': { name: 'Luxiachy', family: "'Luxiachy', serif" },
  'm-plus-rounded-1c': { name: 'M PLUS Rounded 1c', family: "'M PLUS Rounded 1c', sans-serif" },
  'made-canvas': { name: 'MADE Canvas', family: "'MADE Canvas', serif" },
  'made-mirage': { name: 'MADE Mirage', family: "'MADE Mirage', serif" },
  'mali': { name: 'Mali', family: "'Mali', cursive" },
  'marcellus': { name: 'Marcellus', family: "'Marcellus', serif" },
  'margarine': { name: 'Margarine', family: "'Margarine', cursive" },
  'marko-one': { name: 'Marko One', family: "'Marko One', serif" },
  'marmelad': { name: 'Marmelad', family: "'Marmelad', sans-serif" },
  'martel': { name: 'Martel', family: "'Martel', serif" },
  'marvel': { name: 'Marvel', family: "'Marvel', sans-serif" },
  'mate': { name: 'Mate', family: "'Mate', serif" },
  'maven-pro': { name: 'Maven Pro', family: "'Maven Pro', sans-serif" },
  'medio': { name: 'Medio', family: "'Medio', serif" },
  'merriweather': { name: 'Merriweather', family: "'Merriweather', serif" },
  'merriweather-sans': { name: 'Merriweather Sans', family: "'Merriweather Sans', sans-serif" },
  'metal-mania': { name: 'Metal Mania', family: "'Metal Mania', cursive" },
  'metamorphous': { name: 'Metamorphous', family: "'Metamorphous', cursive" },
  'metrophobic': { name: 'Metrophobic', family: "'Metrophobic', sans-serif" },
  'michroma': { name: 'Michroma', family: "'Michroma', sans-serif" },
  'milonga': { name: 'Milonga', family: "'Milonga', cursive" },
  'molgan': { name: 'Molgan', family: "'Molgan', sans-serif" },
  'molle': { name: 'Molle', family: "'Molle', cursive" },
  'monda': { name: 'Monda', family: "'Monda', sans-serif" },
  'monofur': { name: 'Monofur', family: "'Monofur', monospace" },
  'monoton': { name: 'Monoton', family: "'Monoton', cursive" },
  'monsieur-la-doulaise': { name: 'Monsieur La Doulaise', family: "'Monsieur La Doulaise', cursive" },
  'monument-extended': { name: 'Monument Extended', family: "'Monument Extended', sans-serif" },
  'montserrat': { name: 'Montserrat', family: "'Montserrat', sans-serif" },
  'mountains-of-christmas': { name: 'Mountains of Christmas', family: "'Mountains of Christmas', cursive" },
  'mr-dafoe': { name: 'Mr Dafoe', family: "'Mr Dafoe', cursive" },
  'mulish': { name: 'Mulish', family: "'Mulish', sans-serif" },
  'neucha': { name: 'Neucha', family: "'Neucha', cursive" },
  'neuton': { name: 'Neuton', family: "'Neuton', serif" },
  'new-rocker': { name: 'New Rocker', family: "'New Rocker', cursive" },
  'nfs': { name: 'NFS', family: "'NFS', sans-serif" },
  'nixie-one': { name: 'Nixie One', family: "'Nixie One', cursive" },
  'nobile': { name: 'Nobile', family: "'Nobile', sans-serif" },
  'norican': { name: 'Norican', family: "'Norican', cursive" },
  'noto-sans': { name: 'Noto Sans', family: "'Noto Sans', sans-serif" },
  'noto-serif': { name: 'Noto Serif', family: "'Noto Serif', serif" },
  'nova-mono': { name: 'Nova Mono', family: "'Nova Mono', monospace" },
  'nunito': { name: 'Nunito', family: "'Nunito', sans-serif" },
  'nunito-sans': { name: 'Nunito Sans', family: "'Nunito Sans', sans-serif" },
  'old-standard-tt': { name: 'Old Standard TT', family: "'Old Standard TT', serif" },
  'oleo-script': { name: 'Oleo Script', family: "'Oleo Script', cursive" },
  'one-day': { name: 'One Day', family: "'One Day', sans-serif" },
  'open-sans': { name: 'Open Sans', family: "'Open Sans', sans-serif" },
  'orbitron': { name: 'Orbitron', family: "'Orbitron', sans-serif" },
  'oregano': { name: 'Oregano', family: "'Oregano', cursive" },
  'oswald': { name: 'Oswald', family: "'Oswald', sans-serif" },
  'overlock': { name: 'Overlock', family: "'Overlock', cursive" },
  'overpass': { name: 'Overpass', family: "'Overpass', sans-serif" },
  'pacifico': { name: 'Pacifico', family: "'Pacifico', cursive" },
  'palatino': { name: 'Palatino', family: 'Palatino, serif' },
  'passion-one': { name: 'Passion One', family: "'Passion One', cursive" },
  'pathway-gothic-one': { name: 'Pathway Gothic One', family: "'Pathway Gothic One', sans-serif" },
  'patrick-hand': { name: 'Patrick Hand', family: "'Patrick Hand', cursive" },
  'patua-one': { name: 'Patua One', family: "'Patua One', cursive" },
  'paytone-one': { name: 'Paytone One', family: "'Paytone One', sans-serif" },
  'permanent-marker': { name: 'Permanent Marker', family: "'Permanent Marker', cursive" },
  'philosopher': { name: 'Philosopher', family: "'Philosopher', sans-serif" },
  'pinyon-script': { name: 'Pinyon Script', family: "'Pinyon Script', cursive" },
  'pirata-one': { name: 'Pirata One', family: "'Pirata One', cursive" },
  'play': { name: 'Play', family: "'Play', sans-serif" },
  'playball': { name: 'Playball', family: "'Playball', cursive" },
  'playfair-display': { name: 'Playfair Display', family: "'Playfair Display', serif" },
  'playfair-display-sc': { name: 'Playfair Display SC', family: "'Playfair Display SC', serif" },
  'poppins': { name: 'Poppins', family: "'Poppins', sans-serif" },
  'prata': { name: 'Prata', family: "'Prata', serif" },
  'press-start-2p': { name: 'Press Start 2P', family: "'Press Start 2P', cursive" },
  'proza-libre': { name: 'Proza Libre', family: "'Proza Libre', sans-serif" },
  'pt-mono': { name: 'PT Mono', family: "'PT Mono', monospace" },
  'pt-sans': { name: 'PT Sans', family: "'PT Sans', sans-serif" },
  'pt-sans-caption': { name: 'PT Sans Caption', family: "'PT Sans Caption', sans-serif" },
  'pt-sans-narrow': { name: 'PT Sans Narrow', family: "'PT Sans Narrow', sans-serif" },
  'pt-serif': { name: 'PT Serif', family: "'PT Serif', serif" },
  'quantico': { name: 'Quantico', family: "'Quantico', sans-serif" },
  'quattrocento': { name: 'Quattrocento', family: "'Quattrocento', serif" },
  'quattrocento-sans': { name: 'Quattrocento Sans', family: "'Quattrocento Sans', sans-serif" },
  'quesha': { name: 'Quesha', family: "'Quesha', sans-serif" },
  'questrial': { name: 'Questrial', family: "'Questrial', sans-serif" },
  'quicksand': { name: 'Quicksand', family: "'Quicksand', sans-serif" },
  'raleway': { name: 'Raleway', family: "'Raleway', sans-serif" },
  'rambla': { name: 'Rambla', family: "'Rambla', sans-serif" },
  'ranchers': { name: 'Ranchers', family: "'Ranchers', cursive" },
  'red-hat-display': { name: 'Red Hat Display', family: "'Red Hat Display', sans-serif" },
  'reem-kufi': { name: 'Reem Kufi', family: "'Reem Kufi', sans-serif" },
  'righteous': { name: 'Righteous', family: "'Righteous', cursive" },
  'risque': { name: 'Risque', family: "'Risque', cursive" },
  'roboto': { name: 'Roboto', family: "'Roboto', sans-serif" },
  'roboto-condensed': { name: 'Roboto Condensed', family: "'Roboto Condensed', sans-serif" },
  'roboto-mono': { name: 'Roboto Mono', family: "'Roboto Mono', monospace" },
  'roboto-slab': { name: 'Roboto Slab', family: "'Roboto Slab', serif" },
  'rochester': { name: 'Rochester', family: "'Rochester', cursive" },
  'rock-salt': { name: 'Rock Salt', family: "'Rock Salt', cursive" },
  'rokkitt': { name: 'Rokkitt', family: "'Rokkitt', serif" },
  'rosarivo': { name: 'Rosarivo', family: "'Rosarivo', serif" },
  'rubik': { name: 'Rubik', family: "'Rubik', sans-serif" },
  'russo-one': { name: 'Russo One', family: "'Russo One', sans-serif" },
  'sacramento': { name: 'Sacramento', family: "'Sacramento', cursive" },
  'sahitya': { name: 'Sahitya', family: "'Sahitya', serif" },
  'sail': { name: 'Sail', family: "'Sail', cursive" },
  'saira': { name: 'Saira', family: "'Saira', sans-serif" },
  'sanchez': { name: 'Sanchez', family: "'Sanchez', serif" },
  'sansita': { name: 'Sansita', family: "'Sansita', sans-serif" },
  'satoshi': { name: 'Satoshi', family: "'Satoshi', sans-serif" },
  'satisfy': { name: 'Satisfy', family: "'Satisfy', cursive" },
  'secular-one': { name: 'Secular One', family: "'Secular One', sans-serif" },
  'sf-sports-night': { name: 'SF Sports Night', family: "'SF Sports Night', sans-serif" },
  'shadows-into-light': { name: 'Shadows Into Light', family: "'Shadows Into Light', cursive" },
  'shojumaru': { name: 'Shojumaru', family: "'Shojumaru', cursive" },
  'signika': { name: 'Signika', family: "'Signika', sans-serif" },
  'six-caps': { name: 'Six Caps', family: "'Six Caps', sans-serif" },
  'slackey': { name: 'Slackey', family: "'Slackey', cursive" },
  'source-code-pro': { name: 'Source Code Pro', family: "'Source Code Pro', monospace" },
  'source-sans-pro': { name: 'Source Sans Pro', family: "'Source Sans Pro', sans-serif" },
  'source-serif-pro': { name: 'Source Serif Pro', family: "'Source Serif Pro', serif" },
  'space-mono': { name: 'Space Mono', family: "'Space Mono', monospace" },
  'special-elite': { name: 'Special Elite', family: "'Special Elite', cursive" },
  'spectral': { name: 'Spectral', family: "'Spectral', serif" },
  'squada-one': { name: 'Squada One', family: "'Squada One', cursive" },
  'sriracha': { name: 'Sriracha', family: "'Sriracha', cursive" },
  'strait': { name: 'Strait', family: "'Strait', sans-serif" },
  'supercharge': { name: 'Supercharge', family: "'Supercharge', sans-serif" },
  'sweet-bread': { name: 'Sweet Bread', family: "'Sweet Bread', sans-serif" },
  'syncopate': { name: 'Syncopate', family: "'Syncopate', sans-serif" },
  'tahoma': { name: 'Tahoma', family: 'Tahoma, sans-serif' },
  'tangerine': { name: 'Tangerine', family: "'Tangerine', cursive" },
  'teko': { name: 'Teko', family: "'Teko', sans-serif" },
  'telex': { name: 'Telex', family: "'Telex', sans-serif" },
  'times-new-roman': { name: 'Times New Roman', family: "'Times New Roman', serif" },
  'tinos': { name: 'Tinos', family: "'Tinos', serif" },
  'titillium-web': { name: 'Titillium Web', family: "'Titillium Web', sans-serif" },
  'trebuchet-ms': { name: 'Trebuchet MS', family: "'Trebuchet MS', sans-serif" },
  'trocchi': { name: 'Trocchi', family: "'Trocchi', serif" },
  'ubuntu': { name: 'Ubuntu', family: "'Ubuntu', sans-serif" },
  'ubuntu-condensed': { name: 'Ubuntu Condensed', family: "'Ubuntu Condensed', sans-serif" },
  'ubuntu-mono': { name: 'Ubuntu Mono', family: "'Ubuntu Mono', monospace" },
  'ultra': { name: 'Ultra', family: "'Ultra', serif" },
  'unica-one': { name: 'Unica One', family: "'Unica One', cursive" },
  'unifrakturmaguntia': { name: 'UnifrakturMaguntia', family: "'UnifrakturMaguntia', cursive" },
  'unkempt': { name: 'Unkempt', family: "'Unkempt', cursive" },
  'unlock': { name: 'Unlock', family: "'Unlock', cursive" },
  'unna': { name: 'Unna', family: "'Unna', serif" },
  'varela': { name: 'Varela', family: "'Varela', sans-serif" },
  'varela-round': { name: 'Varela Round', family: "'Varela Round', sans-serif" },
  'verdana': { name: 'Verdana', family: 'Verdana, sans-serif' },
  'vidaloka': { name: 'Vidaloka', family: "'Vidaloka', serif" },
  'volkhov': { name: 'Volkhov', family: "'Volkhov', serif" },
  'vollkorn': { name: 'Vollkorn', family: "'Vollkorn', serif" },
  'voltaire': { name: 'Voltaire', family: "'Voltaire', sans-serif" },
  'wallpoet': { name: 'Wallpoet', family: "'Wallpoet', cursive" },
  'walter-turncoat': { name: 'Walter Turncoat', family: "'Walter Turncoat', cursive" },
  'work-sans': { name: 'Work Sans', family: "'Work Sans', sans-serif" },
  'xenosphere': { name: 'Xenosphere', family: "'Xenosphere', sans-serif" },
  'xeroda': { name: 'Xeroda', family: "'Xeroda', sans-serif" },
  'yanone-kaffeesatz': { name: 'Yanone Kaffeesatz', family: "'Yanone Kaffeesatz', sans-serif" },
  'yeseva-one': { name: 'Yeseva One', family: "'Yeseva One', cursive" },
  'ysabeau': { name: 'Ysabeau', family: "'Ysabeau', sans-serif" },
  'yuruy': { name: 'Yuruy', family: "'Yuruy', sans-serif" },
  'zilla-slab': { name: 'Zilla Slab', family: "'Zilla Slab', serif" },
};

// Type definition for the font targets
export type FontTarget = 'primary' | 'secondary' | 'body' | 'accent';